import nodemailer from 'nodemailer';

export const sendFeedbackEmail = async (req, res) => {
    try {
        const { name, email, thoughts, rating } = req.body;

        if (!name || !email || !thoughts || rating === undefined) {
            return res.status(400).json({ success: false, message: 'Please provide all required fields (name, email, thoughts, rating).' });
        }

        const emailUser = process.env.EMAIL_USER;
        const emailPass = process.env.EMAIL_PASS;

        if (!emailUser || !emailPass) {
            console.error('Nodemailer Error: EMAIL_USER or EMAIL_PASS is missing in .env');
            return res.status(500).json({ success: false, message: 'Server email configuration is missing.' });
        }

        // Create a transporter using Gmail
        const transporter = nodemailer.createTransport({
            service: 'gmail',
            auth: {
                user: emailUser,
                pass: emailPass
            }
        });

        // Email layout
        const mailOptions = {
            from: `FuelFit Feedback <${emailUser}>`,
            to: emailUser, // Sending to the admin (yourself)
            replyTo: email, // Set reply-to as the user's email so admin can reply directly!
            subject: `New FuelFit Feedback from ${name}`,
            html: `
                <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e2e8f0; border-radius: 10px;">
                    <h2 style="color: #3AA33A; text-align: center;">New FuelFit Feedback 💬</h2>
                    <hr style="border: 0; height: 1px; background: #e2e8f0; margin: 20px 0;">
                    <p><strong>Name:</strong> ${name}</p>
                    <p><strong>Email:</strong> ${email}</p>
                    <p><strong>Rating:</strong> ${rating} / 5 ⭐</p>
                    <p><strong>Thoughts:</strong></p>
                    <div style="background-color: #f8fafc; padding: 15px; border-radius: 5px; color: #334155; font-style: italic;">
                        "${thoughts}"
                    </div>
                    <hr style="border: 0; height: 1px; background: #e2e8f0; margin: 20px 0;">
                    <p style="font-size: 12px; color: #94a3b8; text-align: center;">This message was automatically generated by the FuelFit Feedback System.</p>
                </div>
            `
        };

        // Send the email
        await transporter.sendMail(mailOptions);

        return res.status(200).json({ success: true, message: 'Feedback sent successfully.' });
    } catch (error) {
        console.error('Error sending feedback email:', error);
        return res.status(500).json({ success: false, message: 'Failed to send feedback email.' });
    }
};
